# Generated by Django 3.1.2 on 2020-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20201007_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='recommand',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
