# Generated by Django 3.1.3 on 2020-11-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20201007_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='nickname',
            new_name='user',
        ),
    ]
