# Generated by Django 3.1.1 on 2020-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('sqaure_image', models.ImageField(blank=True, upload_to='champion_image')),
                ('loading_image', models.ImageField(blank=True, upload_to='champion_image')),
                ('bio', models.TextField()),
                ('line', models.ManyToManyField(blank=True, related_name='champions', to='champions.Line')),
                ('position', models.ManyToManyField(blank=True, related_name='champions', to='champions.Position')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
