# Generated by Django 3.1.1 on 2020-09-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='sqaure_image',
            new_name='square_image',
        ),
    ]
