# Generated by Django 3.1.1 on 2020-09-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='의류', max_length=50),
        ),
        migrations.AlterField(
            model_name='origin',
            name='name',
            field=models.CharField(default='Korea', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.Meterial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.origin'),
        ),
    ]
